FROM marquezproject/marquez
RUN printf 'server:\n  applicationConnectors:\n    - type: http\n      port: 5000\n  adminConnectors:\n    - type: http\n      port: 5001\ndb:\n  driverClass: org.postgresql.Driver\n  url: jdbc:postgresql://marquez-db:5432/marquez\n  user: marquez\n  password: marquez\nlogging:\n  level: INFO\n' > /marquez-config.yml
ENV MARQUEZ_CONFIG=/marquez-config.yml
